site_name: Tic Tac Toe Docs

theme:
  name: "material"

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [src, frontend]

nav:
  - Tic Tac Toe Docs: index.md
  - How-To Guides: how-to-guides.md
  - Reference: reference.md
  - Explanations: explanation.md
  - Tutorials: tutorials.md
